# Numpy Lesson Plan and Hacks
> The outline for our lesson plan and hacks
- toc: true
- categories: []
- type: ap
- week: 29

## Lesson Plan

- The lesson will cover various topics about Numpy and how to use it to perform various functions
    - How to manipulate pixels on images
    - How to manipulate arrays

## What is NumPy? ##

- Numpy is a **python library** used for working with arrays, matrices, and other mathematical operations
- NumPy stands for **Numerical Python**
- Practical applications include **Machine Learning, Data Analysis, Image Processing, and Finance**

# Getting Started #

We first need to import the library. Run the following line of code.

In [2]:
import numpy as np

# 2. Using NumPy to create arrays
- We are going to create a numpy **array** using the **np.array()** function.
- Below is an example of a 1D array.
- We can use arrays like these to **store data and indexing**

In [2]:
a = np.array([1, 2, 3])
print(a) 
# this creates a 1D array

[1 2 3]


How could you create a 3D array based on knowing how to make a 1D array?

In [ ]:
# create 3D array here

In [8]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(c.reshape(1, 9)) # organizes it all in a single line of output

[[1 2 3 4 5 6 7 8 9]]


In [15]:
print(c[1:, :2])
# the 1: means "start at row 1 and select all the remaining rows"
# the :2 means "select the first two columns"

[[4 5]
 [7 8]]


# 3. Basic array operations
- We can do some simple mathematical operations using arrays 
- The mathematical functions are operated on the index value of each array. 

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b) # adds each value based on the column the integer is in
print(a - b) # subtracts each value based on the column the integer is in
print(a * b) # multiplies each value based on the column the integer is in
print(a / b) # divides each value based on the column the integer is in

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


# 4. Data analysis using numpy
- Show how numpy can be used for data analysis tasks, such as finding the mean, median, and standard deviation of a dataset

In [24]:
data = np.array([2, 5, 12, 13, 19])
print(np.mean(data)) # finds the mean of the dataset
print(np.median(data)) # finds the median of the dataset
print(np.std(data)) # finds the standard deviation of the dataset
print(np.min(data)) # finds the min of the dataset
print(np.max(data)) # finds the max of the dataset

10.2
12.0
6.04648658313239
2
19


In [1]:
data = np.genfromtxt('padres.csv', delimiter=',') # delimeter explains that the values are seperated by commas
print(data)
print(np.mean(data[:, 1]))

NameError: name 'np' is not defined

Now from learning this, can you find a different way from how we can solve the sum or products of a dataset other than how we learned before?

In [ ]:
# create a different way of solving the sum or products of a dataset from what we learned above

## Hack Scoring
- 0.3 for solving the lesson problem sets (popcorn hacks)
- 0.6 for solving the hacks
- 0.1 for going extra (such as showing unique code segments using numpy)

## Hacks

1. Write a Python function that takes a 2D numpy array as input and returns the indices of the rows that have at least 1 element greater than 10.

2. Write a Python function that takes a 2D numpy array as input and returns the indices of the elements that are local maxima (greater than their neighbors in both directions).

In [ ]:
import numpy as np

def Greaterthan10(x):
    # write code here
    return

array = np.array([1, 2, 11], [4, 15, 6])
Greaterthan10(array)


In [ ]:
import numpy as np

def LocalMaxima(x):
    # write code here
    return

array = np.array([5, -17, 21], [6, 7, -3])
LocalMaxima(array)